"""Add game_user Association Table

Revision ID: 2d99e417591a
Revises: 4765d455bc75
Create Date: 2023-10-11 01:36:45.948629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d99e417591a'
down_revision = '4765d455bc75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
