"""Add game_user Association Table

Revision ID: 4765d455bc75
Revises: 07c796ed07a7
Create Date: 2023-10-11 01:35:18.618323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4765d455bc75'
down_revision = '07c796ed07a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
