"""Add game_user Association Table

Revision ID: 76528e74fda7
Revises: 2d99e417591a
Create Date: 2023-10-11 01:37:40.442471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76528e74fda7'
down_revision = '2d99e417591a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
